- hosts: all
  become: yes
  tasks:
     - name: remove old version docker
       apt:
           name: docker
           state: absent
       become: true
       
     - name: remove docker.io
       apt:
           name: docker.io
           state: absent
       become: true
       
     - name: remove docker-engine
       apt:
           name: docker-engine
           state: absent
       become: true
       
     - name: Update apt-get repo and cache
       become: true
       apt: 
           update_cache: yes
           force_apt_get: yes 
           cache_valid_time: 3600 
    
     - name: Install a list of packages
       apt:
         pkg:
         - ca-certificates
         - curl
         - gnupg
         - lsb-release
    
     - name: Add Docker’s official GPG key
       apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
      	  state: present
    
     - name: Update apt-get repo and cache
       become: true
       apt: 
           update_cache: yes
           force_apt_get: yes 
           cache_valid_time: 3600
     
     - name: set the stable repository
         apt_repository:
           repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    
     - name: Install a list of packages
       apt:
         pkg:
         - docker-ce
         - docker-ce-cli
         - containerd.io
        
     - name: download the current stable release of Docker Compose
       apt:
           url:"https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"
           state: present
